### ISSUE TITLE
Appreciation and usage

### ISSUE THREAD

**Issue by hummy123** [josephg/crdt-benchmarks#1]
Hi @josephg. 

This isn't an issue at all, but I wanted to give my thanks to you for creating these data sets and opening an issue seemed the best way to do that. I found it helpful for getting benchmarks on a data structure that tries to combine the rope and piece table in OCaml and I think my library wouldn't have been as good without these data sets.

I think one thing that may possibly be helpful to mention in the readme is that consumers might find it easier to use these edit traces by writing a code generator rather than trying to deserialise the .json files into instances of classes. 

.NET (I originally wrote the aforementioned library in F#) and probably some other platforms like Java don't like arrays with elements of different types so it might be easier, but that's a very minor nitpick.

Thanks again for your work on these data sets,
Humza

**Comment by josephg** [comment]
Oh thanks for chiming in and saying so! I'm glad you found them useful.

I'm never sure when I do things like this if the data sets will be used, or if they'll or just sit in obscurity.

> .NET (I originally wrote the aforementioned library in F#) and probably some other platforms like Java don't like arrays with elements of different types

Yeah its really easy to do this sort of data munging in javascript, but I can totally see how this would be harder to parse in C#. I wonder if its worth throwing in some example parser code in C# into the repository. Sounds like you figured it out anyway!
