### ISSUE TITLE
Readme inaccuracy

### ISSUE THREAD

**Issue by hummy123** [josephg/crdt-benchmarks#3]
Hi there. Thanks again for providing these data sets. 

I saw that [others](https://github.com/CeleritasCelery/rune/issues/17#issuecomment-1446690404) were using the data sets you provided for benchmarks (there sure seem to be a lot of us 😅) and thought it might be helpful to someone out there to correct a minor inaccuracy.

The readme states:

> Position in the document. This number should be specified in unicode codepoints, which is the same as the string.length field **when all characters in the document are ASCII (as is the case now)**.

I used your data sets for testing [my library](https://github.com/hummy123/ocaml-piecerope) (which works in UTF-8 although I might/possibly should change it), which is how I found out that there were some non-ASCII (as in larger than 8 bytes) code points in two of the data sets: rustcode.json (which contains ÷, ¿, ƒ and ’) and seph-blog1.json (which contain ↑ and → because of the SVGs, including the deleted one).

Just thought it was worth mentioning in case anyone runs into any issues doubting the correctness of their code. I'm not sure if you would want to update the readme to remove the statement about only ASCII being used or if you would prefer to list the non-ASCII characters. (I think making a list could be more helpful to others but it might clutter the readme so you likely know better.)

**Comment by josephg** [comment]
Thanks - good spotting. I'll fix this up. I ran into this problem myself the other day when I was trying to benchmark a package which assumed UTF8 byte offsets.

**Comment by josephg** [comment]
I've added an ASCII only copy of all the data sets in the `ascii_only/` directory, which should make it easier to use these data sets for benchmarking. And I've [written up a big blurb about the problem in the readme](https://github.com/josephg/crdt-benchmarks#unicode-lengths-oh-my). Let me know if there's anything in here I'm missing!

**Comment by hummy123** [comment]
That looks good to me!
